version: 3

tasks:
  update-version:
    desc: Update the version in all protoc-gen-uuidhelper-* plugin folders
    vars:
      VERSION:
        sh: gitversion
    cmd: |
      for dir in ./cmd/protoc-gen-uuidhelper-*; do
        if [ -d "$dir" ]; then
          echo "package main
      var version = \"{{.VERSION}}\"
      func (b *backend) Version() string {
          return version
      }" > "$dir/version.go"
        fi
        done
  build-go:
    desc: Build the Go plugin
    deps:
      - update-version
    cmds:
      - go build -o protoc-gen-uuidhelper-go cmd/protoc-gen-uuidhelper-go/*.go
  run-go:
    desc: Run the Go plugin
    deps:
      - update-version
    cmds:
      - go run cmd/protoc-gen-uuidhelper-go/*.go -v
  build-kotlin:
    desc: Build the Kotlin plugin
    deps:
      - update-version
    cmds:
      - go build -o protoc-gen-uuidhelper-kotlin cmd/protoc-gen-uuidhelper-kotlin/*.go
  run-kotlin:
    desc: Run the Kotlin plugin
    deps:
      - update-version
    cmds:
      - go run cmd/protoc-gen-uuidhelper-kotlin/*.go -v
  install-go:
    desc: Install the Go plugin
    deps:
      - build-go
    cmds:
      - cp protoc-gen-uuidhelper-go ~/go/bin/protoc-gen-uuidhelper-go
  install-kotlin:
    desc: Install the Kotlin plugin
    deps:
      - build-kotlin
    cmds:
      - cp protoc-gen-uuidhelper-kotlin ~/go/bin/protoc-gen-uuidhelper-kotlin
  install:
    desc: Install all plugin
    deps:
      - install-go
      - install-kotlin
  clean-go:
    desc: Clean up generated Go files
    cmd: fd -g '*.pb.go' internal/test/gen/go -x rm {}
  clean-kotlin:
    desc: Clean up generated Kotlin files
    cmd: fd . -e kt -e java internal/test/gen/kotlin -x rm {}
  clean:
    desc: Clean up generated files
    deps:
      - clean-go
      - clean-kotlin
  proto-go:
    desc: Generate Go protobuf files
    cmd: fd -t f -e proto -0 | xargs -0 protoc -I internal/test --go_out=internal/test/gen/go --go_opt=paths=source_relative --uuidhelper-go_out=internal/test/gen/go --uuidhelper-go_opt=paths=source_relative
  proto-kotlin:
    desc: Generate Kotlin protobuf files
    cmd: fd -t f -e proto -0 | xargs -0 protoc -I internal/test --java_out=internal/test/gen/kotlin --kotlin_out=internal/test/gen/kotlin --plugin=./protoc-gen-uuidhelper-kotlin --uuidhelper-kotlin_out=internal/test/gen/kotlin --uuidhelper-kotlin_opt=paths=source_relative,threadLocalBuffer=false
  proto:
    desc: Generate protobuf files
    deps:
      - clean
      - proto-go
      - proto-kotlin
  test-go:
    desc: Run tests
    deps:
      - proto-go
    cmds:
      - go test -parallel 8 -v ./...
